blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import views
from search import views
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('', include('homepage.urls')),
    path('user/', include('posts.urls')),
    path('user/', include("accounts.urls")),


    path('admin/', admin.site.urls),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/homepage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
app_name = 'posts'
urlpatterns = [
    path('', views.home, name='home-page'),
    path('about/', views.aboutus, name='about-us'),
    path('contact/', views.contact, name='contact'),
    path('create/', views.create, name='create'),
    #path('profile/', views.profile, name='profile'),
    #path('login/', views.login, name='login'),
    path('search/',  views.search, name='search'),
    path('myblogs/', views.ViewBlogs, name="Views"),
    path('myblogs/<slug:slug>', views.blogDetail, name='detail'),
    path('like/', views.like_post, name='like-post'),
    path('read/<slug:slug>', views.blogRead, name='read'),

]

blog/templates/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <script src="https://kit.fontawesome.com/21f148cdb3.js" crossorigin="anonymous"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/about_us_style.css' %}">
    <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <title>About Us</title>
	</head>
	<body>
		<!-- ===============navbar====================== -->
		<div class="navbar" id="myTopnav">
      		<a href="index.html" class="logo"><img src="{% static 'images/logo1.png' %}" style="width: 100%"></a>
      		<a href="javascript:void(0);" class="icon" onclick="Function()"><i class="fa fa-bars"></i></a>
			<button onclick="myFunction()"><i class="fas fa-adjust"></i></button>
			{% if user.is_authenticated %}
			<a href="/user/profile">Hello, {{ user.first_name }}</a>
			<a href="/user/logout">Logout</a>
			{% else %}
  			<a href="/login/login">Sign In/Up</a>
			{% endif %}
			{% if user.is_authenticated %}
      		<a href="/create">Create Blog</a>
			{% else %}
			<a href="/login/login">Create Blog</a>
			{% endif %}
      		<a href="/contact">Contact</a>
  			<a href="/">Home</a>
      		<form class="example" action="#">
      			<input type="text" placeholder="Search for blog..." name="search bar">
      			<button type="submit"><i class="fa fa-search"></i></button>
      		</form>
		</div>
		<!-- ==============================cards about us============================== -->
		<div class="row">
		  {% for dt in user %}
  			<div class="rightcolumn">
			
    			<div class="card">
				
      				<div class="row2">
  						<div class="column2 ">
    						<div class="card2">
      							<img src="{% static 'images/img_avatar.png' %}" alt="Avatar" >
                  				<div class="container">
                    				<h4><b>Name: {{ dt.first_name }}</b></h4>
                    				<p>Some info about that person</p>
                    				<a href="#"><i class="fab fa-facebook"></i></a>
      								      <a href="#"><i class="fab fa-instagram"></i></a>
      								      <a href="#"><i class="fab fa-twitter"></i></a>
      								      <a href="#"><i class="fab fa-linkedin-in"></i></a>
      								      <a href="#"><i class="fas fa-at"></i></a>
      								      <a href="#"><i class="fab fa-whatsapp"></i></a>
                  				</div>
                    		</div>
  						</div>
  						
					</div>
					
				</div>
				
    		</div>	
			{%  endfor %}
  		</div>

  			<!-- ======footer=================== -->
			<div class="footer" >
      			<a href="#"><i class="fab fa-facebook"></i></a>
      			<a href="#"><i class="fab fa-instagram"></i></a>
      			<a href="#"><i class="fab fa-twitter"></i></a>
      			<a href="#"><i class="fab fa-linkedin-in"></i></a>
      			<a href="#"><i class="fas fa-at"></i></a>
      			<a href="#"><i class="fab fa-whatsapp"></i></a>
  				<h5>&copy; <script>document.write(new Date().getFullYear())</script> blogsite, Inc. All rights reserved.</h5>
			</div>

		<script src="{% static 'js/about_us_script.js' %}"></script>
		<!-- ==========back to top========================== -->
		<a class="gotopbtn" href="#"> <i class="fas fa-arrow-up"></i> </a>

	</body>
<>

blog/templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <script src="https://kit.fontawesome.com/21f148cdb3.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'styles/blog_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Blog</title>
	</head>
	<body onload="loadingfunction()">
    <div id="loading"></div>
    <!-- =============navbar=================== -->
		<div class="navbar" id="myTopnav">
      <a href="/" class="logo"><img src="{% static 'images/logo1.png' %}" style="width: 100%"></a>
      <a href="javascript:void(0);" class="icon" onclick="Function()"><i class="fa fa-bars"></i></a>
			<button onclick="myFunction()"><i class="fas fa-adjust"></i></button>
          {% if user.is_authenticated %}
          <a href="user/profile">Hello, {{ user.first_name }}</a>
          <a href="user/logout">Logout</a>
          {% else %}
  		<a href="user/login">Sign In/Up</a>
          {% endif %}
          {% if user..is_authenticated %}
          <a href="/create">Create Blog</a>
          {% else %}
      <a href="user/login">Create Blog</a>
          {% endif %}
      <a href="/contact">Contact</a>
  		<a href="/about">About Us</a>
      <form class="example" action="#">
        <input type="text" placeholder="Search for blog..." name="query" id="query">
        <button type="submit"><i class="fa fa-search"></i></button>
      </form>
		</div>
    <!-- ================blog====================== -->
    {% for bl in blog %}
		<div class="header">
      <h2>Blog Name: {{ bl.title }}</h2>
    </div>
    {% endfor %}
    <div class="row">
      <!-- ===================div on left=================== -->
      <div class="leftcolumn">
          {% block content %}
          {% for bl in blog %}
        <div class="card">
          <h2>TITLE HEADING: {{ bl.title }}</h2>
          <h5>Short description, Date</h5>
          <div class="fakeimg" style="height:200px;">Image</div>
          <p>{{ bl.editor | safe }}</p>
            <form method="post" action="{% url 'posts:like-post' %}">
                {% csrf_token %}
          <div class="like-content">
            <button class="btn-secondary like-review" type="submit" name="post_id" value="{{ bl.id }}">
              <i class="fa fa-heart" aria-hidden="true"></i> Like
            </button>

          </div>
                 </form>
        </div>

      </div>
        {% endfor %}
        {% endblock %}
      <!-- ===================div on right================ -->
      <div class="rightcolumn">
        {% for bl in blog %}
        <div class="card">
          <h2>About Me</h2>
          <div class="column2 ">
            <div class="card2">
              <img src="{% static 'images/img_avatar.png' %}" alt="Avatar" >
              <div class="container">
                <h4><b>Name: {{ bl.author }}</b></h4>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        <div class="card">
          <h3>Popular Posts</h3>
              <div class="column3">
                <div class="card3">
                  <img src="{% static 'images/2.jpg' %}" alt="Avatar" style="width:100%">
                  <div class="container3">
                    <h4><b>Blog Heading 1</b></h4>
                    <p>Some intro of blog</p>
                  </div>
                    <a href="blog.html">read full</a>
                </div>
              </div>
              <div class="column3">
                <div class="card3">
                  <img src="{% static 'images/2.jpg' %}" alt="Avatar" style="width:100%">
                  <div class="container3">
                    <h4><b>Blog Heading 1</b></h4>
                    <p>Some intro of blog</p>
                  </div>
                    <a href="blog.html">read full</a>
                </div>
              </div>
        </div>

        <div class="card">
          <h3>Follow Me</h3>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin-in"></i></a>
          <a href="#"><i class="fas fa-at"></i></a>
          <a href="#"><i class="fab fa-whatsapp"></i></a>
        </div>

      </div>

    </div>
    <!-- ==========footer================== -->
		<div class="footer" >
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin-in"></i></a>
      <a href="#"><i class="fas fa-at"></i></a>
      <a href="#"><i class="fab fa-whatsapp"></i></a>
  		<h5>&copy; <script>document.write(new Date().getFullYear())</script> blogsite, Inc. All rights reserved.</h5>
		</div>

		<script src="{% static 'js/blog_script.js' %}"></script>
    <!-- ===========back to top=============== -->
    <a class="gotopbtn" href="#"> <i class="fas fa-arrow-up"></i> </a>
	</body>
</html>

blog/templates/blogread.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <script src="https://kit.fontawesome.com/21f148cdb3.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'styles/blog_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Blog</title>
	</head>
	<body onload="loadingfunction()">
    <div id="loading"></div>
    <!-- =============navbar=================== -->
		<div class="navbar" id="myTopnav">
      <a href="/" class="logo"><img src="{% static 'images/logo1.png' %}" style="width: 100%"></a>
      <a href="javascript:void(0);" class="icon" onclick="Function()"><i class="fa fa-bars"></i></a>
			<button onclick="myFunction()"><i class="fas fa-adjust"></i></button>
          {% if user.is_authenticated %}
          <a href="user/profile">Hello, {{ user.first_name }}</a>
          <a href="user/logout">Logout</a>
          {% else %}
  		<a href="user/login">Sign In/Up</a>
          {% endif %}
          {% if user..is_authenticated %}
          <a href="/create">Create Blog</a>
          {% else %}
      <a href="user/login">Create Blog</a>
          {% endif %}
      <a href="/contact">Contact</a>
  		<a href="/about">About Us</a>
      <form class="example" action="#">
        <input type="text" placeholder="Search for blog..." name="query" id="query">
        <button type="submit"><i class="fa fa-search"></i></button>
      </form>
		</div>
    <!-- ================blog====================== -->

		<div class="header">
      <h2>Blog Name: {{ blog.title }}</h2>
    </div>
    
    <div class="row">
      <!-- ===================div on left=================== -->
      <div class="leftcolumn">
          {% block content %}
         
        <div class="card">
          <h2>TITLE HEADING: {{ bl.title }}</h2>
          <h5>Short description, Date</h5>
          <div class="fakeimg" style="height:200px;">Image</div>
          <p>{{ blog.editor | safe }}</p>
            <form method="post" action="{% url 'posts:like-post' %}">
                {% csrf_token %}
          <div class="like-content">
            <button class="btn-secondary like-review" type="submit" name="post_id" value="{{ blog.id }}">
              <i class="fa fa-heart" aria-hidden="true"></i> Like
            </button>

          </div>
                 </form>
        </div>

      </div>
       
        {% endblock %}
      <!-- ===================div on right================ -->
      <div class="rightcolumn">
       
        <div class="card">
          <h2>About Me</h2>
          <div class="column2 ">
            <div class="card2">
              <img src="{% static 'images/img_avatar.png' %}" alt="Avatar" >
              <div class="container">
                <h4><b>Name: {{ blog.author }}</b></h4>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <h3>Popular Posts</h3>
              <div class="column3">
                <div class="card3">
                  <img src="{% static 'images/2.jpg' %}" alt="Avatar" style="width:100%">
                  <div class="container3">
                    <h4><b>Blog Heading 1</b></h4>
                    <p>Some intro of blog</p>
                  </div>
                    <a href="blog.html">read full</a>
                </div>
              </div>
              <div class="column3">
                <div class="card3">
                  <img src="{% static 'images/2.jpg' %}" alt="Avatar" style="width:100%">
                  <div class="container3">
                    <h4><b>Blog Heading 1</b></h4>
                    <p>Some intro of blog</p>
                  </div>
                    <a href="blog.html">read full</a>
                </div>
              </div>
        </div>

        <div class="card">
          <h3>Follow Me</h3>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin-in"></i></a>
          <a href="#"><i class="fas fa-at"></i></a>
          <a href="#"><i class="fab fa-whatsapp"></i></a>
        </div>

      </div>

    </div>
    <!-- ==========footer================== -->
		<div class="footer" >
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin-in"></i></a>
      <a href="#"><i class="fas fa-at"></i></a>
      <a href="#"><i class="fab fa-whatsapp"></i></a>
  		<h5>&copy; <script>document.write(new Date().getFullYear())</script> blogsite, Inc. All rights reserved.</h5>
		</div>

		<script src="{% static 'js/blog_script.js' %}"></script>
    <!-- ===========back to top=============== -->
    <a class="gotopbtn" href="#"> <i class="fas fa-arrow-up"></i> </a>
	</body>
</html>

blog/templates/body.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- ==== Linked CSS ==== -->
    <link rel="stylesheet" href="{% static 'styles/styling.css' %}">

    <!-- ==== jquery link ==== -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- ==== Font Awesome 5 LINK ==== -->
    <script src="https://kit.fontawesome.com/287d476af5.js" crossorigin="anonymous"></script>
    <title>User Profile</title>
</head>
<body>
    <div class="container">

        <header>
            <div class="logo">
               <a href="#"><img src="{% static 'images/logo.png' %}" alt="Website Logo"></a>
            </div>

            <!-- === when in mobile view this logo will be seen === -->
            <div class="mobile-logo">
                <a href="#"><img src="{% static 'images/short logo.png' %}" alt=""></a>
            </div>

            <div class="bars">
                <span><i class="fas fa-bars"></i></span>
            </div>

            <div class="nav">
                <ul>
                    <li>
                       <h3><a href="/about/">About</a></h3>
                    </li>

                    <li>
                        <h3><a href="/contact/">Contact</a></h3>
                    </li>
                    <l1><a href="/user/logout/">Logout</a></l1>
                    <li class="active">
                        <h3><a href="#">Profile</a></h3>
                    </li>
                </ul>
            </div>
        </header>

        <!-- === Nav for mobile === -->
        <div class="nav-mobile">
            <ul>
                <li>
                    <span><i class="far fa-address-card"></i></span>
                   <h3><a href="#">About</a></h3>
                </li>

                <li>
                    <span><i class="fas fa-phone-alt"></i></span>
                    <h3><a href="#">Contact</a></h3>
                </li>

                <li class="active">
                    <span><i class="fas fa-user"></i></span>
                    <h3><a href="#">Profile</a></h3>
                </li>
            </ul>
        </div>
        
        <!-- === Side Slide Bar === -->
        <div class="m-bar">
           <span><i class="fas fa-ellipsis-v"></i></span>
        </div>
        <div class="container_2">
            <aside class="sidebar">
               <h1>Sidebar<span class="close"><i class="fas fa-times"></i></span></h1>
               <div class="user-side">
                   <div class="user-pic">
                       <img width="80" src="{% static 'images/user.png' %}" alt="user-profile-pic">
                   </div>
                   <div class="user-info">
                        <span class="name">user8091</span>
                        <span class="mail">user8091@gmail.com</span>
                        <span class="status">Online</span>
                   </div>
               </div>

               <div class="side-nav">
                   <h2>General</h2>
                    <nav>
                        <ul>
                            <li class="active" onclick="show(0)">
                                <span><i class="fas fa-user"></i></span>
                                <h3>User Profile</h3>
                            </li>

                            <li onclick="show(1)">
                                <span><i class="fab fa-blogger-b"></i></span>
                                <h3>My BLOGS</h3>
                            </li>

                            <li onclick="show(2)">
                                <span><i class="fas fa-heart"></i></span>
                                <h3>Favourite</h3>
                            </li>
                             
                            <li onclick="show(3)">
                                <span><i class="fas fa-plus"></i></span>
                                <h3>Create</h3>
                            </li>
                        </ul>
                    </nav>
               </div>
            </aside>
   
            <div class="main">

                <!-- === user profile === -->
                <section class="profile tabs">
                    <div class="profile">
                        <!-- === USERNAME FORM === -->
                        <form action="#" class="user_name">
                            <div class="top">
                                <!-- === USER PROFILE PIC AND EDIT BUTTON === -->
                                <button class="btn"><i class="far fa-edit"></i></button>

                                <div class="user_img">
                                    <img src="{% static 'img/user.png' %}" alt="user image">
                                </div>

                                <!-- === USER NAME AND EDIT === -->
                                <div class="user">
                                    <input type="text" class="name_2" placeholder="USER8091">

                                    <div class="edit_name-button">
                                        <button class="btn_2"><i class="far fa-edit"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="bottom">
                                <!-- ==== SOCIAL MEDIA ==== -->
                                <div class="user_socialmedia">
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-facebook"></i></a>
                                </div>

                                <!-- ==== BLOG INFO ==== -->
                                <div class="blogs">3 <span>Blogs</span></div>
                                <div class="border"></div>
                                <div class="followers">2k <span>Followers</span></div>
                                <div class="border"></div>
                                <div class="following">43 <span>Following</span></div>
                            </div>
                        </form>
                    </div>
                </section>

                <!-- === my blogs === -->
                <section class="tabs">

                    <div class="userpost">
                        <!-- POST 1 -->
                        <div class="post">
                            <div class="post_img">
                               <img src="{% static 'images/25630.jpg' %}" alt="Green tea">
                            </div>

                            <div class="post_text">
                                <span>4 days ago</span>
                                <h2>Green Tea</h2>
                                <p>Green tea is a type of tea that is made from Camellia sinensis leaves and buds and it is good for mind.</p>
                                <a href="#">More...</a>
                            </div>
              
                        </div>

                        <!-- POST 2 -->
                        <div class="post">
                            <div class="post_img">
                               <img src="{% static 'images/south africa.jpg' %}" height="200" alt="cape town beach">
                            </div>

                            <div class="post_text">
                                <span>1 month ago</span>
                                <h2>Beauty of S.Africa</h2>
                                <p>South Africa, renowned for its great natural beauty, thats why it is a favourate destination of travelers</p>
                                <a href="#">More...</a>
                            </div>
                   
                        </div>
                        <!-- POST 3 -->
                        <div class="post">
                            <div class="post_img">
                               <img src="{% static 'images/1876.jpg' %}" height="200" alt="space">
                            </div>

                            <div class="post_text">
                                <span>1 year ago</span>
                                <h2>Space Explorer</h2>
                                <p>The Space Explorer game where you can explore the planets, asteroids, and galaxy by clicking on them.</p>
                                <a href="#">More...</a>
                            </div>
                     
                        </div>   
                    </div>
                </section>

                <!-- === favourite === -->
                <section class="tabs">

                    <div class="likeblogs">

                         <!-- POST 1 -->
                         <div class="post">
                            <div class="post_img">
                               <img src="{% static 'images/south africa.jpg' %}" height="200" alt="cape town beach">
                            </div>

                            <div class="post_text">
                                <span>1 month ago</span>
                                <h2>Beauty of S.Africa</h2>
                                <p>South Africa, renowned for its great natural beauty, thats why it is a favourate destination of travelers</p>
                                <a href="#">More...</a>
                            </div>
                 
                        </div>

                        <!-- POST 2 -->
                        <div class="post">
                            <div class="post_img">
                               <img src="{% static 'images/1876.jpg' %}" height="200" alt="space">
                            </div>

                            <div class="post_text">
                                <span>1 year ago</span>
                                <h2>Space Explorer</h2>
                                <p>The Space Explorer game where you can explore the planets, asteroids, and galaxy by clicking on them.</p>
                                <a href="#">More...</a>
                            </div>
             
                        </div>   
                    </div>
                </section>


<!-- ========================== CREATE BLOG ============================ -->
                <section class="tabs">
                    <div class="create">
                        <h1>create your blog</h1>
                    </div>
                </section>
            </div>
        </div> 
    </div>
    <!-- ==== js ==== -->
    <script src="{% static 'styles/coolness.js' %}"></script>
</body>
</html>

blog/templates/myposts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ blog.title }}{% endblock %}</title>
</head>
<body>
{% block content %}
{% for bl in blog %}
<h3>{{ bl.author }}</h3>
<h3>{{ bl.title }}</h3>
{% endfor %}


{% endblock %}
</body>
</html>

blog/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration </title>
</head>
<body>
    <form action="/user/register/" method="post">
        {% csrf_token %}
        <input type="text" name="first_name" placeholder="First Name"><br>
        <input type="text" name="last_name"  placeholder="Last Name"><br>
        <input type="email" name="email" placeholder="Email"><br>
        <input type="text" name="username" placeholder="Username"><br>
        <input type="password" name="password1" placeholder="Password"><br>
        <input type="password" name="password2" placeholder="Confirm Password"><br>
        <input type="submit">
    </form>
</body>
</html>

blog/templates/user_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://kit.fontawesome.com/21f148cdb3.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/user-blog_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>User Blog</title>
  </head>
  <body onload="loadingfunction()">
    <div id="loading"></div>
    <!-- =================nav bar================== -->
    <div class="navbar" id="myTopnav">
      <a href="/" class="logo"><img src="{% static 'images/logo1.png' %}" style="width: 100%"></a>
      <a href="javascript:void(0);" class="icon" onclick="Function()"><i class="fa fa-bars"></i></a>
      <button onclick="myFunction()"><i class="fas fa-adjust"></i></button>
      <a href="/contact">Contact</a>
      <a href="/about"">About Us</a>
      <form class="example" action="#">
        <input type="text" placeholder="Search for blog..." name="search bar">
        <button type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
    <!-- ====================card========================= -->
    <div class="row">
      <!-- ===================filter==================== -->
      <div class="filterleftside">
        <div>
          <a class="btn" href="/user/profile"> Profile</a>
          <a class="btn active1" href="user_blog.html"> My Blogs</a>
          <a class="btn" href="/user/favourites"> Favourites</a>
        </div>
        <h2 style="text-align: center;">Filter's</h2>
          <div id="myBtnContainer">
            <button class="btn active" onclick="filterSelection('all')"> Show all</button>
            <h3 style="text-align: center;">Topic</h3>
              {% for cat in cat %}
              {% if cat.topic == "Technology" %}
            <button class="btn" onclick="filterSelection('tech')"> Technology </button>
            {% endif %}
            {% if cat.topic == "Mathematics" %}
            <button class="btn" onclick="filterSelection('math')"> Mathematics</button>
            {% endif %}
            {% if cat.topic == "Social Media" %}
            <button class="btn" onclick="filterSelection('social')"> Social Media</button>
            {% endif %}
            {% endfor %}
          </div>
      </div>


      <div class="rightcolumn">
        <div class="card">
          <div class="row2">
            <h3 style="text-align: center;">Your Blogs</h3>
            {% for bl in blog %}
            <div class="column2 filterDiv english tech">
              <div class="card2">
                <img src="{% static 'images/2.jpg' %}" alt="Avatar" style="width:100%">
                <div class="container">
                  <h4><b>Blog Heading: {{bl.title }}</b></h4>
                  <p>Some intro of blog: {{ bl.editor | safe | truncatewords:"30" | linebreaks }}</p>
                </div>
                <a class='readmore' href="{% url 'posts:detail' slug=bl.slug %}">Read Full</a>
              </div>
            </div>
            {% endfor %}



          </div><!-- row2 -->
          <!-- ==================pagination=================== -->
          <div class="pagination">
            <a href="#">&laquo;</a>
            <a class="active" href="#1">1</a>
            <a href="#2">2</a>
            <a href="#3">3</a>
            <a href="#4">4</a>
            <a href="#5">5</a>
            <a href="#6">6</a>
            <a href="#">&raquo;</a>
          </div>

        </div>
      </div>
    </div>
    <!-- ===============footer====================== -->
    <div class="footer" >
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin-in"></i></a>
      <a href="#"><i class="fas fa-at"></i></a>
      <a href="#"><i class="fab fa-whatsapp"></i></a>
      <h5>&copy; <script>document.write(new Date().getFullYear())</script> blogsite, Inc. All rights reserved.</h5>
    </div>

    <script src="{% static 'js/user_blog_script.js' %}"></script>
    <!-- ======================go to top==================== -->
    <a class="gotopbtn" href="#"> <i class="fas fa-arrow-up"></i> </a>

  </body>
</html>